# Generated by Django 6.0.7 on 2026-07-26 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_rename_order_date_order_date_remove_order_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='keyword',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
